sprite $grails [100x105/16z] {
xPhPagKW38ORie3E-x_lW2Ao10IqPcuwLNtJVPhFFmia77z-VktN_fyfZSJ6sisPjOO9jFfqVM2xEziACmJVS1IQJLZ_CaRrMe7fh7-QPVrAWdFHzeHm8JAh
FbEuFKau6SxMA0hiCy4jReDjPjfZceSrH2CrwwP9W3S34mXsX7qQCID5sp_RlgqWx6WUmxQlYJZzDGB18zZxK3A941X1xAFvAZCiF29U-Eao673KkeXJIDTT
iB-Lu13Use7Ns_uIOKw4CQqwKNR_H8GtRa3C_YuEvaOOWwsK-aH2C123ySfD9KBqLjDJAoAyqMZQJiSXCLtbr6TEQWeH0svV8SgmgqzJAeOzbv6lQwwgxJvc
N2gnZf2oAOFKz8HHKqYHLBpUzb4pjKpHAw-ti9ovC4ajLPO4h2A0YoZ5fwKoaVYjg_XGuNv0T9NlA-rgYynbgb7bghiNMsDWdSsneQggRItgNWON5ZABXUfU
4e9SLsS8YDiERLPqWDOip4QQJL6lTq3ySnU-eOtLGbAL1smCYFQXAFwgpRoti3hw85O8-dF8bCLKOP_BZylIfHXqEZAgz3zEJIn7XKELPdm5dSNILZG5SGYi
q-nco8tm5CGZL9LcXnreqoWx3y7XmgYl6uveKCQmLROg71lm50cE2fuA1MBQcnGOou_-0ZB2Xv15Hgt4-TGQwfQyTYBgJwY082RC6S8Eej1rQ6s7kRMS22M0
JuJ0a8Bism2MjMZ_jCBT4b0WE3jZpjccNhiMpgPF2Q5cPk7pv7qK41B3DLJvVyKJkfpkDOUp8jS8Vbsw2CwErIYPj88M9VKoEIGYCdUTiQQR41XO37GswRtG
D4OZbml9OGT5nYQ8KwKM-lpmJoe_rRGiusvnD5M8CuvAw8tfkfqn3I5ef5CRAmA5bOJscmLNPGD5mO1xYoAHmNM3ts2e8c_lg0T6RNWTHzKC835uYQ4lhrlp
pE1qNzB3ZEknh7bYvA6TOSH2i-Le6f8HWvFw3Eem8D-HMemwHMi6j1Zw7foRlifBJMJGpS2cgwe9AsNm4uDw34ZRmiBm-lsJZh21wtlJ5REg6EEoWfQtZFIW
onyt4uA4zJbKrtCEAUj3y0WsPUH2qlqrA-Y24PzNfNk-78qo8fmhJ1ZfNX8FelpimgQCVB26Xexil4lyhj8E8yO2gvDU9tkV8Jm78a1fnpYF-IowOMu2J2Ek
cZEfYJShN5G7PNvdwXaACgAtk6bv8wMmJq2n7TVLWpTLT25u8bHhWkyWTDqbjZKWwkPWsl6KrB2t4T2-9sWRIErk3Q07H1U2qbWWQo3iVeUhMz7W-YlcKWRU
fXxk8qJ4qIYxmbINPUKsXn0XSHaMsi05HDrozEkv9WnzdvxtPoFhfuZ1xvyLpY5I6x-Q0Af6bI42pjnw-PSmHbGK8YRll80UPI2jYuZxAi-uQUsL1eqT2VG5
eKl1hmZdgnFu58SlNifnMrDxzmFGFz-Otm8n8ntBV_nQaUVuvkR-QaTzlFwl_JFx2m00
}

