sprite $groovy [100x50/16z] {
jLZRTkCW30HiRaQ2___RbGG6uYIdU9FeeMcnmw3Hw4ALkccxKJytW9z3583yOuW0tltQ4q3lVuoHmPC1_X32GFG2idrhnmXehfeI28_mDP6IFR82hc9u-9P6
jLB8FxfXzFwB81nNOiH366iE_C3uF4cSG83QPx9WmeXWFjOFI3ZKDfqtJn1VI1A0NIAkxC3G46SCzo5R02c8hbGQNC636wnVzr4oPuKL0pibU87uZArCPmSv
U1OSiSI5IZOc9obBGkMIA7J1xo944e5TJKxwQivAN0XmW81coKScI2mTzHDo-qH-O4xS9zF66AtrB1y5bg787MFWtAwP-4J6Pz_gKaKME7K1qRAxskID56Cy
Ka8w4Ae3Mhy3YKecOlP2tjKDCeC45hZTM7fRuvVteSGYduRnjtKxElHAnBmAgn0LorFsXT8AcEKF3fCgx8zYSSbP99Tg16VfpG8t11DxIMt-2bJkphjM8McP
dPA6fQe-UEzSixRhBn0Z-uigcAeY6PzUQT-dbSF9O_xBySAUQr3Wo9L2gCZag1L6ZixHrMoBQezlgO1gxm77Mc9gYj8X70GjIxd5Ji71nxFlTMjhMCyTeQOY
gex1-lHACWAmrE8fJo9jsmBopeNH8sWBEMxXxJUkKqqpDHmxgnRjKBgSln1OgNDHXfKKzBqFOliSdhL7UMgM9mFqSaPE-BKUMqBWI9Pf6psbrwXY4Q1rohsl
hGmKjfK7Cp1DeyMFHk_R4hRAF64i5FrQ6HxyocUcPkQ24ZQUDIgSCqg2ipEkJ5-NOOIFAcV4NhEuHU7vMwlnOuPPgVbmN3L06OMPDdNkG4pFVQHMwLO5rZ3c
TtQfPB4cjNzfRgx9FYzXuCGLCkCoXxm1E6jVDPTXyOAIQumjdep_RTqLlHPpwRAfHtSDGsbk5yUBUBungNBiHLp7cChtujoGd22zvXx3TJ7Xm_YtRZXwuqGx
MitP_VXe3ARt8CoJ6oIuDc5lUNPc6XdplQ7h4SAH271x4D-O0Q3sL8TmxnPNu99bh-wuZRFGy-FcpDkJBX97_as9niQP4wIR0saVBuwpZRnDs7uQl7dTRLmZ
_1t4ewiPzjjky8IqT5lIpPbRrrqFaOLKxWpxyX-8SaUtL4Tkto6bBwv3eFslQ-Hw2lhqoONunU8_
}

