sprite $micronaut [77x63/16z] {
xLT9beKW31GGcSdzRziCAeDeAx3eHMVntqUWI4YbW6Nvjxb6YmOUmWA0r600SW1hSs0iHuO1C5HC5m1c94p4KDPYT58cjebPxTukVkwvaAYrUSum9s-Ts2VY
1B6QOZ9nFTiti7PmmcCNd7aYFS2HDSfRQvcHFNHRba3n67E37mcD6jI9OkGUUMngqI4LHoIg34drH9ZoBikKQJxWsM4hdbfCFgMeNo_eWUCmKEJ4mOuebA4a
q2i60E3aLF5F-L4QG8TlwWRB3G1KWpNeuiLx3Vqgdr4Qkv1xkoZlLcVgbYpCecfiLSoaFb4eF6S5uMnkBLhhvmFfifXm_Z3MGGcR12Yd6O4Ui4WdgKfPNUGU
iVAzH7-alDWdniYTmqS7zJ-Vt5JUCmw9ozxVCnlK1bRAlihSk4kBnZCEFpUjmSxFO34mi5d5rPttEiPRqfFJllQ6YhiAkDPc1Cl6OxBKP_6pQaIbRwW6kWYL
X5jnGL6Tue2Zgh0bPw7XXkhPNmiganyJXfDmrrixRbUYB2zov63MLUyYOxO3H9NUYFKaxFePIz-SwFT9VDIZA4LKxKrTikIzvCgSl6ERNv1RG-zflWO_cfSw
9DBX2MyL9vGaQqcwE1TyfxQN9v9LsLFgusrxCUNzaASd4pzNmOPqxI7DAtlO-CntqoH3V_Obx1b0SjKSUvniUHrHilpRTFi1
}

